name: Racket Puncher GitHub Actions
on:
  push:
    branches: [main]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'racket-puncher-front'
          git config --global user.email 'racket-puncher@example.com'
          echo "racket-puncher.shop" > CNAME
          git add CNAME
          git commit -m "Add CNAME file"
          git push origin main
          npm run deploy
