name: Racket Puncher GitHub Actions
on:
  push:
    branches: [main]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build the application
        run: npm run build --if-present

      - name: Deploy to GitHub Pages
        run: |
          git checkout gh-pages
          rm -rf *
          mv build/* ./
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages